import { Empresa, Tenant, Contrato, Usuario } from "./types";

export const MOCK_EMPRESAS: Empresa[] = [
  { id: "1", nombre: "Extra Life", razonSocial: "Extra Life SpA", nombreFantasia: "ExtraLife", pais: "Chile", idFiscal: "96603490-5", giro: "Retail", direccion: "Av. Apoquindo 4501, Las Condes", nombreContacto: "Tamara Alve", cargo: "CEO", correoContacto: "contacto@amplifica.io", telefonoPrincipal: "CL +56 9 1234 5678", planes: ["Express"], contratos: 3, estadoComercial: "Al día", estado: "Activo", habilitado: true },
  { id: "2", nombre: "ChileanBazar", razonSocial: "ChileanBazar SpA", nombreFantasia: "ChileanBazar", pais: "Chile", idFiscal: "76820690-5", giro: "Comercio electrónico", direccion: "Calle Falsa 123", nombreContacto: "Pedro Muñoz", cargo: "CTO", correoContacto: "pedro@chileanbazar.cl", telefonoPrincipal: "CL +56 9 8765 4321", planes: ["Envíos Pro"], contratos: 0, estadoComercial: "Vencido", estado: "Inactivo", habilitado: false },
  { id: "3", nombre: "MarketPlaceChile", razonSocial: "MarketPlaceChile SpA", nombreFantasia: "MarketPlaceChile", pais: "Chile", idFiscal: "77100200-K", giro: "Marketplace", direccion: "Teatinos 280, Santiago", nombreContacto: "Laura Soto", cargo: "CFO", correoContacto: "laura@mpc.cl", telefonoPrincipal: "CL +56 9 1111 2222", planes: ["Express"], contratos: 1, estadoComercial: "Por vencer", estado: "Activo", habilitado: true },
  { id: "4", nombre: "E-ShopChile", razonSocial: "E-ShopChile SpA", nombreFantasia: "E-ShopChile", pais: "Chile", idFiscal: "76300100-1", giro: "E-commerce", direccion: "Gran Av. José Miguel Carrera 7890", nombreContacto: "Carlos Vera", cargo: "Ops", correoContacto: "carlos@eshop.cl", telefonoPrincipal: "CL +56 9 3333 4444", planes: [], contratos: 2, estadoComercial: "Al día", estado: "Activo", habilitado: true },
  { id: "5", nombre: "PatagoniaICom", razonSocial: "PatagoniaICom SpA", nombreFantasia: "PatagoniaICom", pais: "Chile", idFiscal: "76500200-3", giro: "Logística", direccion: "Camino Lo Barnechea 1234", nombreContacto: "Ana Reyes", cargo: "CEO", correoContacto: "ana@patagonia.cl", telefonoPrincipal: "CL +56 9 5555 6666", planes: ["Envíos Pro", "Multicanal"], contratos: 3, estadoComercial: "Al día", estado: "Activo", habilitado: true },
  { id: "6", nombre: "SantiagoMarket", razonSocial: "SantiagoMarket SpA", nombreFantasia: "SantiagoMarket", pais: "Chile", idFiscal: "76700300-5", giro: "Retail", direccion: "Av. Libertador Bernardo O'Higgins 1234", nombreContacto: "Mario Rojas", cargo: "Dir. Comercial", correoContacto: "mario@sm.cl", telefonoPrincipal: "CL +56 9 7777 8888", planes: [], contratos: 0, estadoComercial: "Inactivo", estado: "Inactivo", habilitado: false },
  { id: "7", nombre: "ChileCart", razonSocial: "ChileCart SpA", nombreFantasia: "ChileCart", pais: "Chile", idFiscal: "76900100-7", giro: "E-commerce", direccion: "Pío Nono 360, Providencia", nombreContacto: "Sofía Castro", cargo: "CEO", correoContacto: "sofia@chilecart.cl", telefonoPrincipal: "CL +56 9 9999 0000", planes: ["Envíos Pro"], contratos: 1, estadoComercial: "Al día", estado: "Activo", habilitado: true },
];

export const MOCK_TENANTS: Tenant[] = [
  { id: "0021", empresaId: "1", razonSocial: "AndesCommerce SpA", nombre: "AndesCommerce", dominio: "www.andescommerce.com", pais: "Chile", zonaHoraria: "America/Santiago", moneda: "CLP", couriers: true, planes: ["Express", "Envíos Pro", "Multicanal"], contratos: 2, estado: "Activo", habilitado: true },
  { id: "0022", empresaId: "2", razonSocial: "ChileanBazar SpA", nombre: "ChileanBazar", dominio: "www.chileanbazar.cl", pais: "Chile", zonaHoraria: "America/Santiago", moneda: "CLP", couriers: false, planes: [], contratos: 0, estado: "Inactivo", habilitado: false },
  { id: "0023", empresaId: "3", razonSocial: "ManuelPacaChile SpA", nombre: "ManuelPacaChile", dominio: "www.mpc.cl", pais: "Chile", zonaHoraria: "America/Santiago", moneda: "CLP", couriers: true, planes: ["Express"], contratos: 1, estado: "Activo", habilitado: true },
  { id: "0024", empresaId: "4", razonSocial: "E-ShopChile SpA", nombre: "E-ShopChile", dominio: "www.eshop.cl", pais: "Chile", zonaHoraria: "America/Santiago", moneda: "CLP", couriers: true, planes: ["Multicanal"], contratos: 2, estado: "Activo", habilitado: true },
  { id: "0025", empresaId: "5", razonSocial: "PatagoniaICom SpA", nombre: "PatagoniaICom", dominio: "www.patagonia.cl", pais: "Chile", zonaHoraria: "America/Santiago", moneda: "CLP", couriers: true, planes: ["Envíos Pro", "Multicanal"], contratos: 3, estado: "Activo", habilitado: true },
];

export const MOCK_CONTRATOS: Contrato[] = [
  { id: "0001", empresaId: "1", tenantId: "0021", tenantNombre: "Extra Life", nombre: "Extra Life", razonSocial: "Extra Life SpA", planes: ["Envíos Pro", "Express"], fechaInicio: "2025-01-01", fechaVencimiento: "2026-01-01", moneda: "CLP", monto: 250000, plazoVencer: "382 días", estado: "Activo", habilitado: true },
  { id: "0002", empresaId: "1", tenantId: "0021", tenantNombre: "Amplifica", nombre: "Amplifica", razonSocial: "Amplifica SpA", planes: ["Express"], fechaInicio: "2025-06-01", fechaVencimiento: "2025-07-01", moneda: "CLP", monto: 150000, plazoVencer: "30 Días", estado: "Activo", habilitado: true },
  { id: "0003", empresaId: "1", tenantId: "0021", tenantNombre: "Amplifica", nombre: "Amplifica", razonSocial: "Amplifica SpA", planes: ["Multicanal"], fechaInicio: "2024-01-01", fechaVencimiento: "2025-01-01", moneda: "CLP", monto: 300000, plazoVencer: "15 Días", estado: "Vencido", habilitado: false },
  { id: "0004", empresaId: "5", tenantId: "0025", tenantNombre: "Amplifica", nombre: "Amplifica", razonSocial: "Amplifica SpA", planes: ["Express"], fechaInicio: "2025-03-01", fechaVencimiento: "2026-03-01", moneda: "CLP", monto: 200000, plazoVencer: "15 Días", estado: "Vigente", habilitado: true },
];

export const MOCK_USUARIOS: Usuario[] = [
  { id: "0001", tipo: "Amplifica", nombres: "Jose Antonio Car…", apellidos: "Carreño", telefono: "+56993521190", email: "jose@amplifica.cl", tenantId: "0021", rol: "Super Admin", diasRestantes: 362, estado: "Activo", habilitado: true },
  { id: "0001", tipo: "Amplifica", nombres: "Cristóbal Vila", apellidos: "Vila", telefono: "+56993521192", email: "cristobal@amplifica.cl", tenantId: "0021", rol: "Dev", diasRestantes: 362, estado: "Activo", habilitado: true },
  { id: "0001", tipo: "Amplifica", nombres: "Emiliano Loza", apellidos: "Loza", telefono: "+56993521190", email: "emiliano@amplifica.cl", tenantId: "0021", rol: "Tester", diasRestantes: 362, estado: "Inactivo", habilitado: false },
  { id: "0052", tipo: "Tenant", nombres: "Paola Martínez", apellidos: "Martínez", telefono: "+56993343280", email: "paola@tenant.cl", tenantId: "0022", rol: "nax", diasRestantes: undefined, estado: "Activo", habilitado: true },
  { id: "0053", tipo: "Amplifica", nombres: "Cristian Aceve…", apellidos: "Acevedo", telefono: "+56763011270", email: "cristian@amplifica.cl", tenantId: "0021", rol: "Vendor", diasRestantes: undefined, estado: "Inactivo", habilitado: false },
];
