import { Empresa, Tenant, Contrato, Usuario, TenantMembership, Plan, TrialConfig, AuditLogEntry } from "./types";

const cc = (nombre: string, cargo: string, correo: string, telefono: string) => ({ nombre, cargo, correo, telefono });
const cpMismo = () => ({ mismoQueComercial: true, nombre: "", cargo: "", correo: "", telefono: "" });
const cp = (nombre: string, cargo: string, correo: string, telefono: string) => ({ mismoQueComercial: false, nombre, cargo, correo, telefono });

export const MOCK_EMPRESAS: Empresa[] = [
  {
    id: "1", nombreFantasia: "Extra Life", nombre: "Extra Life",
    razonSocial: "Extra Life SpA", idFiscal: "96.603.490-5", pais: "Chile",
    giro: "Retail", direccion: "Av. Apoquindo 4501, Las Condes",
    contactoComercial: cc("Tamara Alve", "CEO", "tamara@extralife.cl", "+56 9 1234 5678"),
    contactoPagos: cp("Ana Torres", "CFO", "finanzas@extralife.cl", "+56 9 9876 5432"),
    notasInternas: "Cliente premium. Renovación anual en marzo.",
    planes: ["Express"], contratos: 3, tenants: 2, tenantsTrial: 0,
    operationalStatus: "activo", fechaCreacion: "2023-03-15",
    estadoComercial: "Al día", estado: "Activo", habilitado: true,
  },
  {
    id: "2", nombreFantasia: "ChileanBazar", nombre: "ChileanBazar",
    razonSocial: "ChileanBazar SpA", idFiscal: "76.820.690-5", pais: "Chile",
    giro: "Comercio electrónico", direccion: "Calle Falsa 123, Santiago",
    contactoComercial: cc("Pedro Muñoz", "CTO", "pedro@chileanbazar.cl", "+56 9 8765 4321"),
    contactoPagos: cpMismo(),
    planes: ["Envíos Pro"], contratos: 0, tenants: 1, tenantsTrial: 1,
    operationalStatus: "suspendido", fechaCreacion: "2023-07-22",
    estadoComercial: "Vencido", estado: "Inactivo", habilitado: false,
  },
  {
    id: "3", nombreFantasia: "MarketPlaceChile", nombre: "MarketPlaceChile",
    razonSocial: "MarketPlaceChile SpA", idFiscal: "77.100.200-K", pais: "Chile",
    giro: "Marketplace", direccion: "Teatinos 280, Santiago",
    contactoComercial: cc("Laura Soto", "CFO", "laura@mpc.cl", "+56 9 1111 2222"),
    contactoPagos: cpMismo(),
    planes: ["Express"], contratos: 1, tenants: 1, tenantsTrial: 1,
    operationalStatus: "activo", fechaCreacion: "2024-01-10",
    estadoComercial: "Por vencer", estado: "Activo", habilitado: true,
  },
  {
    id: "4", nombreFantasia: "E-ShopChile", nombre: "E-ShopChile",
    razonSocial: "E-ShopChile SpA", idFiscal: "76.300.100-1", pais: "Colombia",
    giro: "E-commerce", direccion: "Cra. 7 #71-21, Bogotá",
    contactoComercial: cc("Carlos Vera", "Gerente Ops", "carlos@eshop.cl", "+57 300 333 4444"),
    contactoPagos: cp("Valentina Ríos", "Contadora", "pagos@eshop.cl", "+57 300 555 6666"),
    planes: [], contratos: 2, tenants: 1, tenantsTrial: 0,
    operationalStatus: "activo", fechaCreacion: "2024-02-28",
    estadoComercial: "Al día", estado: "Activo", habilitado: true,
  },
  {
    id: "5", nombreFantasia: "PatagoniaICom", nombre: "PatagoniaICom",
    razonSocial: "PatagoniaICom SpA", idFiscal: "76.500.200-3", pais: "Chile",
    giro: "Logística", direccion: "Camino Lo Barnechea 1234, Santiago",
    contactoComercial: cc("Ana Reyes", "CEO", "ana@patagonia.cl", "+56 9 5555 6666"),
    contactoPagos: cpMismo(),
    planes: ["Envíos Pro", "Multicanal"], contratos: 3, tenants: 1, tenantsTrial: 0,
    operationalStatus: "activo", fechaCreacion: "2022-11-05",
    estadoComercial: "Al día", estado: "Activo", habilitado: true,
  },
  {
    id: "6", nombreFantasia: "SantiagoMarket", nombre: "SantiagoMarket",
    razonSocial: "SantiagoMarket SpA", idFiscal: "76.700.300-5", pais: "Chile",
    giro: "Retail", direccion: "Av. Libertador B. O'Higgins 1234",
    contactoComercial: cc("Mario Rojas", "Dir. Comercial", "mario@sm.cl", "+56 9 7777 8888"),
    contactoPagos: cpMismo(),
    planes: [], contratos: 0, tenants: 0, tenantsTrial: 0,
    operationalStatus: "inactivo", fechaCreacion: "2023-05-18",
    estadoComercial: "Inactivo", estado: "Inactivo", habilitado: false,
  },
  {
    id: "7", nombreFantasia: "ChileCart", nombre: "ChileCart",
    razonSocial: "ChileCart SpA", idFiscal: "76.900.100-7", pais: "Perú",
    giro: "E-commerce", direccion: "Av. Larco 1301, Miraflores, Lima",
    contactoComercial: cc("Sofía Castro", "CEO", "sofia@chilecart.cl", "+51 9 9999 0000"),
    contactoPagos: cp("Roberto Lima", "Finanzas", "pagos@chilecart.cl", "+51 9 1111 2222"),
    planes: ["Envíos Pro"], contratos: 1, tenants: 1, tenantsTrial: 1,
    operationalStatus: "activo", fechaCreacion: "2024-08-30",
    estadoComercial: "Al día", estado: "Activo", habilitado: true,
  },
];

export const MOCK_TENANTS: Tenant[] = [
  { id: "0021", empresaId: "1", nombre: "AndesCommerce", dominio: "andescommerce.amplifica.io", billingMode: "pagado", planNombre: "Growth", operationalStatus: "activo", fechaCreacion: "2024-01-15" },
  { id: "0022", empresaId: "2", nombre: "ChileanBazar", dominio: "chileanbazar.amplifica.io", billingMode: "sin_contrato", planNombre: null, operationalStatus: "suspendido", fechaCreacion: "2023-08-10" },
  { id: "0023", empresaId: "3", nombre: "MPC Chile", dominio: "mpc.amplifica.io", billingMode: "trial", planNombre: null, operationalStatus: "activo", fechaCreacion: "2024-06-01" },
  { id: "0024", empresaId: "4", nombre: "E-Shop Colombia", dominio: "eshop-co.amplifica.io", billingMode: "pagado", planNombre: "Enterprise", operationalStatus: "activo", fechaCreacion: "2024-03-20" },
  { id: "0025", empresaId: "5", nombre: "Patagonia Ops", dominio: "patagonia.amplifica.io", billingMode: "pagado", planNombre: "Growth", operationalStatus: "activo", fechaCreacion: "2022-12-01" },
  { id: "0026", empresaId: "1", nombre: "Extra Life MX", dominio: "extralife-mx.amplifica.io", billingMode: "trial", planNombre: null, operationalStatus: "activo", fechaCreacion: "2025-02-10" },
  { id: "0027", empresaId: "7", nombre: "ChileCart Perú", dominio: "chilecart-pe.amplifica.io", billingMode: "pagado", planNombre: "Starter", operationalStatus: "activo", fechaCreacion: "2024-09-15" },
];

export const MOCK_CONTRATOS: Contrato[] = [
  {
    id: "c-001", displayId: "AMP-A3K9F", tenantId: "0021",
    billingMode: "pagado", planId: "plan-2", planNombre: "Growth",
    trialConfigId: null, trialConfigNombre: null,
    fechaInicio: "2025-01-01", fechaVencimiento: "2026-01-01", trialEndDate: null,
    moneda: "CLP", montoBase: 500000, precioPedidoAdicional: 500,
    tipoDescuento: null, valorDescuento: null, montoBaseFinal: 500000,
    overridePedidosMes: null, overrideSucursales: null,
    autoRenew: true, notas: "Renovación anual pactada con el cliente.",
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2025-01-01",
  },
  {
    id: "c-002", displayId: "AMP-B7M2D", tenantId: "0023",
    billingMode: "trial", planId: null, planNombre: null,
    trialConfigId: "trial-1", trialConfigNombre: "Trial Starter 15d",
    fechaInicio: "2025-06-01", fechaVencimiento: "2025-06-16", trialEndDate: "2025-06-16",
    moneda: "CLP", montoBase: null, precioPedidoAdicional: null,
    tipoDescuento: null, valorDescuento: null, montoBaseFinal: null,
    overridePedidosMes: null, overrideSucursales: null,
    autoRenew: false, notas: null,
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2025-06-01",
  },
  {
    id: "c-003", displayId: "AMP-C4P8H", tenantId: "0024",
    billingMode: "pagado", planId: "plan-3", planNombre: "Enterprise",
    trialConfigId: null, trialConfigNombre: null,
    fechaInicio: "2024-04-01", fechaVencimiento: "2025-04-01", trialEndDate: null,
    moneda: "CLP", montoBase: 1200000, precioPedidoAdicional: 300,
    tipoDescuento: "porcentaje", valorDescuento: 10, montoBaseFinal: 1080000,
    overridePedidosMes: 1500, overrideSucursales: null,
    autoRenew: true, notas: "Descuento del 10% por contrato anual. Override de pedidos negociado.",
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2024-03-20",
  },
  {
    id: "c-004", displayId: "AMP-D1R5J", tenantId: "0025",
    billingMode: "pagado", planId: "plan-2", planNombre: "Growth",
    trialConfigId: null, trialConfigNombre: null,
    fechaInicio: "2025-03-01", fechaVencimiento: "2026-03-01", trialEndDate: null,
    moneda: "CLP", montoBase: 450000, precioPedidoAdicional: 500,
    tipoDescuento: "monto_fijo", valorDescuento: 50000, montoBaseFinal: 400000,
    overridePedidosMes: null, overrideSucursales: 8,
    autoRenew: true, notas: "Descuento fijo de $50.000. Override de sucursales a 8.",
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2025-02-15",
  },
  {
    id: "c-005", displayId: "AMP-E6T3N", tenantId: "0026",
    billingMode: "trial", planId: null, planNombre: null,
    trialConfigId: "trial-2", trialConfigNombre: "Trial Enterprise 30d",
    fechaInicio: "2025-02-10", fechaVencimiento: "2025-03-12", trialEndDate: "2025-03-12",
    moneda: "CLP", montoBase: null, precioPedidoAdicional: null,
    tipoDescuento: null, valorDescuento: null, montoBaseFinal: null,
    overridePedidosMes: null, overrideSucursales: null,
    autoRenew: false, notas: null,
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2025-02-10",
  },
  {
    id: "c-006", displayId: "AMP-F2V9Q", tenantId: "0027",
    billingMode: "pagado", planId: "plan-1", planNombre: "Starter",
    trialConfigId: null, trialConfigNombre: null,
    fechaInicio: "2024-10-01", fechaVencimiento: "2025-10-01", trialEndDate: null,
    moneda: "CLP", montoBase: 200000, precioPedidoAdicional: 800,
    tipoDescuento: null, valorDescuento: null, montoBaseFinal: 200000,
    overridePedidosMes: null, overrideSucursales: null,
    autoRenew: false, notas: null,
    estado: "vigente", closureReason: null, closureDate: null, closureNotes: null,
    fechaCreacion: "2024-09-20",
  },
  {
    id: "c-007", displayId: "AMP-G8W1L", tenantId: "0021",
    billingMode: "pagado", planId: "plan-2", planNombre: "Growth",
    trialConfigId: null, trialConfigNombre: null,
    fechaInicio: "2024-01-01", fechaVencimiento: "2025-01-01", trialEndDate: null,
    moneda: "CLP", montoBase: 300000, precioPedidoAdicional: 600,
    tipoDescuento: null, valorDescuento: null, montoBaseFinal: 300000,
    overridePedidosMes: null, overrideSucursales: null,
    autoRenew: false, notas: "Contrato anterior al renovado.",
    estado: "inactivo", closureReason: "vencido", closureDate: "2025-01-01", closureNotes: null,
    fechaCreacion: "2023-12-15",
  },
];

export const MOCK_PLANES: Plan[] = [
  {
    id: "plan-1", nombre: "Starter",
    descripcion: "Plan básico para operaciones pequeñas con despacho y seguimiento.",
    modulos: ["Fulfillment", "Tracking"],
    pedidosMax: 100, sucursalesMax: 2, tenantsActivos: 1,
    estado: "Activo", fechaCreacion: "2024-06-01",
  },
  {
    id: "plan-2", nombre: "Growth",
    descripcion: "Plan intermedio con módulos ampliados para operaciones en crecimiento.",
    modulos: ["Fulfillment", "Devoluciones", "Tracking", "Gestión de inventario", "Gestión de couriers"],
    pedidosMax: 300, sucursalesMax: 5, tenantsActivos: 3,
    estado: "Activo", fechaCreacion: "2024-03-15",
  },
  {
    id: "plan-3", nombre: "Enterprise",
    descripcion: "Plan completo con todos los módulos habilitados para grandes operaciones.",
    modulos: ["Fulfillment", "Devoluciones", "Tracking", "Gestión de inventario", "Reportería avanzada", "Integraciones", "Multi-bodega", "Gestión de couriers"],
    pedidosMax: 1000, sucursalesMax: 20, tenantsActivos: 1,
    estado: "Activo", fechaCreacion: "2024-01-10",
  },
  {
    id: "plan-4", nombre: "Express",
    descripcion: "Plan express orientado a despachos rápidos.",
    modulos: ["Fulfillment", "Tracking", "Gestión de couriers"],
    pedidosMax: 200, sucursalesMax: 3, tenantsActivos: 0,
    estado: "Inactivo", fechaCreacion: "2023-11-20",
  },
];

export const MOCK_TRIAL_CONFIGS: TrialConfig[] = [
  {
    id: "trial-1", nombre: "Trial Starter 15d",
    descripcion: "Trial básico de 15 días para prospectos iniciales.",
    duracionDias: 15, modulos: ["Fulfillment", "Tracking"],
    pedidosMax: 50, sucursalesMax: 1, esDefault: true,
    tenantsActivos: 2, estado: "Activo", fechaCreacion: "2024-06-01",
  },
  {
    id: "trial-2", nombre: "Trial Enterprise 30d",
    descripcion: "Trial extendido de 30 días para empresas grandes en evaluación.",
    duracionDias: 30, modulos: ["Fulfillment", "Devoluciones", "Tracking", "Gestión de inventario", "Gestión de couriers"],
    pedidosMax: 200, sucursalesMax: 3, esDefault: false,
    tenantsActivos: 0, estado: "Activo", fechaCreacion: "2024-08-15",
  },
  {
    id: "trial-3", nombre: "Trial Campaña Q1",
    descripcion: "Trial especial para campaña comercial Q1 2025.",
    duracionDias: 20, modulos: ["Fulfillment", "Tracking", "Devoluciones"],
    pedidosMax: 100, sucursalesMax: 2, esDefault: false,
    tenantsActivos: 1, estado: "Inactivo", fechaCreacion: "2025-01-05",
  },
];

export const MOCK_USUARIOS: Usuario[] = [
  // ── SaaS Admin users ──
  {
    id: "u-001", tipo: "SaaS Admin", nombres: "Fernando", apellidos: "Roblero",
    email: "fernando@amplifica.cl", telefono: "+56993521190",
    memberships: [], rol: "Super Admin",
    estado: "Activo", fechaCreacion: "2024-06-01", ultimoLogin: "2026-03-12T14:30:00Z", creadoPor: "Sistema",
  },
  {
    id: "u-002", tipo: "SaaS Admin", nombres: "Ana", apellidos: "Torres",
    email: "ana.torres@amplifica.cl", telefono: "+56912345678",
    memberships: [], rol: "Comercial",
    estado: "Activo", fechaCreacion: "2024-08-15", ultimoLogin: "2026-03-11T09:15:00Z", creadoPor: "u-001",
  },
  {
    id: "u-003", tipo: "SaaS Admin", nombres: "Diego", apellidos: "Muñoz",
    email: "diego.munoz@amplifica.cl", telefono: "+56987654321",
    memberships: [], rol: "Customer Success",
    estado: "Activo", fechaCreacion: "2024-09-01", ultimoLogin: "2026-03-10T16:45:00Z", creadoPor: "u-001",
  },
  {
    id: "u-004", tipo: "SaaS Admin", nombres: "Laura", apellidos: "Figueroa",
    email: "laura.figueroa@amplifica.cl", telefono: "+56945678901",
    memberships: [], rol: "Operaciones",
    estado: "Activo", fechaCreacion: "2024-10-01", ultimoLogin: "2026-03-08T11:20:00Z", creadoPor: "u-001",
  },
  {
    id: "u-005", tipo: "SaaS Admin", nombres: "Sebastián", apellidos: "Correa",
    email: "sebastian.correa@amplifica.cl", telefono: "+56956789012",
    memberships: [], rol: "Finanzas",
    estado: "Activo", fechaCreacion: "2025-01-10", ultimoLogin: "2026-03-07T08:00:00Z", creadoPor: "u-001",
  },
  // ── Staff Amplifica users ──
  {
    id: "u-006", tipo: "Staff Amplifica", nombres: "Camila", apellidos: "Vásquez",
    email: "camila.vasquez@amplifica.cl", telefono: "+56911223344",
    memberships: [
      { tenantId: "0021", rol: "Soporte", fechaAsignacion: "2025-02-01" },
      { tenantId: "0023", rol: "Soporte", fechaAsignacion: "2025-03-15" },
    ],
    rol: "Soporte",
    estado: "Activo", fechaCreacion: "2025-02-01", ultimoLogin: "2026-03-12T10:00:00Z", creadoPor: "u-001",
  },
  {
    id: "u-007", tipo: "Staff Amplifica", nombres: "Martín", apellidos: "Soto",
    email: "martin.soto@amplifica.cl", telefono: "+56922334455",
    memberships: [
      { tenantId: "0021", rol: "Operaciones de campo", fechaAsignacion: "2025-01-15" },
      { tenantId: "0024", rol: "Operaciones de campo", fechaAsignacion: "2025-04-01" },
      { tenantId: "0025", rol: "Operaciones de campo", fechaAsignacion: "2025-06-01" },
    ],
    rol: "Operaciones de campo",
    estado: "Activo", fechaCreacion: "2025-01-15", ultimoLogin: "2026-03-11T15:30:00Z", creadoPor: "u-001",
  },
  // ── Usuario Tenant ──
  {
    id: "u-008", tipo: "Usuario Tenant", nombres: "Roberto", apellidos: "Mendoza",
    email: "roberto@rapidelivery.cl", telefono: "+56933445566",
    memberships: [
      { tenantId: "0021", rol: "Admin Tenant", fechaAsignacion: "2025-01-01" },
      { tenantId: "0022", rol: "Visor", fechaAsignacion: "2025-06-01" },
    ],
    rol: "Admin Tenant",
    estado: "Activo", fechaCreacion: "2025-01-01", ultimoLogin: "2026-03-12T18:00:00Z", creadoPor: "u-001",
  },
  {
    id: "u-009", tipo: "Usuario Tenant", nombres: "Patricia", apellidos: "Lagos",
    email: "patricia@rapidelivery.cl", telefono: "+56944556677",
    memberships: [
      { tenantId: "0021", rol: "Operador", fechaAsignacion: "2025-02-15" },
    ],
    rol: "Operador",
    estado: "Activo", fechaCreacion: "2025-02-15", ultimoLogin: "2026-03-11T12:00:00Z", creadoPor: "u-008",
  },
  {
    id: "u-010", tipo: "Usuario Tenant", nombres: "Jorge", apellidos: "Aravena",
    email: "jorge@enviosex.cl", telefono: "+56955667788",
    memberships: [
      { tenantId: "0023", rol: "Admin Tenant", fechaAsignacion: "2025-03-01" },
    ],
    rol: "Admin Tenant",
    estado: "Activo", fechaCreacion: "2025-03-01", ultimoLogin: "2026-03-10T09:00:00Z", creadoPor: "u-001",
  },
  {
    id: "u-011", tipo: "Usuario Tenant", nombres: "Valentina", apellidos: "Ruiz",
    email: "valentina@logitech.pe", telefono: "+51987654321",
    memberships: [
      { tenantId: "0024", rol: "Operador", fechaAsignacion: "2025-04-01" },
    ],
    rol: "Operador",
    estado: "Activo", fechaCreacion: "2025-04-01", ultimoLogin: "2026-03-09T14:30:00Z", creadoPor: "u-001",
  },
  {
    id: "u-012", tipo: "Usuario Tenant", nombres: "Carlos", apellidos: "Pinto",
    email: "carlos@mktotal.cl", telefono: "+56966778899",
    memberships: [
      { tenantId: "0025", rol: "Admin Tenant", fechaAsignacion: "2025-05-01" },
      { tenantId: "0026", rol: "Operador", fechaAsignacion: "2025-07-01" },
    ],
    rol: "Admin Tenant",
    estado: "Activo", fechaCreacion: "2025-05-01", ultimoLogin: "2026-03-12T08:45:00Z", creadoPor: "u-002",
  },
  {
    id: "u-013", tipo: "Usuario Tenant", nombres: "Daniela", apellidos: "Reyes",
    email: "daniela@rapidelivery.cl", telefono: "+56977889900",
    memberships: [
      { tenantId: "0021", rol: "Visor", fechaAsignacion: "2026-03-10" },
    ],
    rol: "Visor",
    estado: "Pendiente de activación", fechaCreacion: "2026-03-10", ultimoLogin: null, creadoPor: "u-001",
  },
];

// ── Audit Log ──

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: "al-001", timestamp: "2026-03-12T14:32:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Usuario", entidadId: "u-013", entidadLabel: "Daniela Reyes",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
  {
    id: "al-002", timestamp: "2026-03-12T14:35:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Usuario", entidadId: "u-013", entidadLabel: "Daniela Reyes",
    accion: "Reenviar invitación", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
  {
    id: "al-003", timestamp: "2026-03-11T09:20:00Z",
    usuarioId: "u-002", usuarioNombre: "Ana Torres",
    entidad: "Cliente", entidadId: "3", entidadLabel: "MarketPlaceChile",
    accion: "Editar", campo: "contactoComercial.correo", valorAnterior: "laura.old@mpc.cl", valorNuevo: "laura@mpc.cl",
    ip: "190.20.45.78",
  },
  {
    id: "al-004", timestamp: "2026-03-11T10:15:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Tenant", entidadId: "0026", entidadLabel: "Extra Life MX",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
  {
    id: "al-005", timestamp: "2026-03-10T16:50:00Z",
    usuarioId: "u-003", usuarioNombre: "Diego Muñoz",
    entidad: "Contrato", entidadId: "c-005", entidadLabel: "AMP-E6T3N",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "190.20.45.80",
  },
  {
    id: "al-006", timestamp: "2026-03-10T11:00:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Plan", entidadId: "plan-4", entidadLabel: "Express",
    accion: "Desactivar", campo: "estado", valorAnterior: "Activo", valorNuevo: "Inactivo",
    ip: "200.83.100.12",
  },
  {
    id: "al-007", timestamp: "2026-03-09T14:22:00Z",
    usuarioId: "u-002", usuarioNombre: "Ana Torres",
    entidad: "Cliente", entidadId: "1", entidadLabel: "Extra Life",
    accion: "Editar", campo: "notasInternas", valorAnterior: "Cliente VIP.", valorNuevo: "Cliente premium. Renovación anual en marzo.",
    ip: "190.20.45.78",
  },
  {
    id: "al-008", timestamp: "2026-03-09T09:30:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Contrato", entidadId: "c-001", entidadLabel: "AMP-A3K9F",
    accion: "Editar", campo: "montoBase", valorAnterior: "450000", valorNuevo: "500000",
    ip: "200.83.100.12",
  },
  {
    id: "al-009", timestamp: "2026-03-08T15:10:00Z",
    usuarioId: "u-004", usuarioNombre: "Laura Figueroa",
    entidad: "Tenant", entidadId: "0022", entidadLabel: "ChileanBazar",
    accion: "Suspender", campo: "operationalStatus", valorAnterior: "activo", valorNuevo: "suspendido",
    ip: "190.20.45.82",
  },
  {
    id: "al-010", timestamp: "2026-03-08T10:45:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Usuario", entidadId: "u-009", entidadLabel: "Patricia Lagos",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
  {
    id: "al-011", timestamp: "2026-03-07T08:15:00Z",
    usuarioId: "u-005", usuarioNombre: "Sebastián Correa",
    entidad: "Contrato", entidadId: "c-004", entidadLabel: "AMP-D1R5J",
    accion: "Editar", campo: "valorDescuento", valorAnterior: "30000", valorNuevo: "50000",
    ip: "200.83.100.15",
  },
  {
    id: "al-012", timestamp: "2026-03-07T08:16:00Z",
    usuarioId: "u-005", usuarioNombre: "Sebastián Correa",
    entidad: "Contrato", entidadId: "c-004", entidadLabel: "AMP-D1R5J",
    accion: "Editar", campo: "montoBaseFinal", valorAnterior: "420000", valorNuevo: "400000",
    ip: "200.83.100.15",
  },
  {
    id: "al-013", timestamp: "2026-03-06T12:00:00Z",
    usuarioId: "u-002", usuarioNombre: "Ana Torres",
    entidad: "Cliente", entidadId: "7", entidadLabel: "ChileCart",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "190.20.45.78",
  },
  {
    id: "al-014", timestamp: "2026-03-06T12:30:00Z",
    usuarioId: "u-002", usuarioNombre: "Ana Torres",
    entidad: "Tenant", entidadId: "0027", entidadLabel: "ChileCart Perú",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "190.20.45.78",
  },
  {
    id: "al-015", timestamp: "2026-03-05T17:00:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Trial Config", entidadId: "trial-3", entidadLabel: "Trial Campaña Q1",
    accion: "Desactivar", campo: "estado", valorAnterior: "Activo", valorNuevo: "Inactivo",
    ip: "200.83.100.12",
  },
  {
    id: "al-016", timestamp: "2026-03-05T11:30:00Z",
    usuarioId: "u-003", usuarioNombre: "Diego Muñoz",
    entidad: "Contrato", entidadId: "c-007", entidadLabel: "AMP-G8W1L",
    accion: "Desactivar", campo: "estado", valorAnterior: "vigente", valorNuevo: "inactivo",
    ip: "190.20.45.80",
  },
  {
    id: "al-017", timestamp: "2026-03-04T09:00:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Plan", entidadId: "plan-2", entidadLabel: "Growth",
    accion: "Editar", campo: "pedidosMax", valorAnterior: "250", valorNuevo: "300",
    ip: "200.83.100.12",
  },
  {
    id: "al-018", timestamp: "2026-03-03T14:20:00Z",
    usuarioId: "u-004", usuarioNombre: "Laura Figueroa",
    entidad: "Tenant", entidadId: "0023", entidadLabel: "MPC Chile",
    accion: "Editar", campo: "dominio", valorAnterior: "mpcchile.amplifica.io", valorNuevo: "mpc.amplifica.io",
    ip: "190.20.45.82",
  },
  {
    id: "al-019", timestamp: "2026-03-02T10:00:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Cliente", entidadId: "6", entidadLabel: "SantiagoMarket",
    accion: "Desactivar", campo: "operationalStatus", valorAnterior: "activo", valorNuevo: "inactivo",
    ip: "200.83.100.12",
  },
  {
    id: "al-020", timestamp: "2026-03-01T08:45:00Z",
    usuarioId: "u-002", usuarioNombre: "Ana Torres",
    entidad: "Usuario", entidadId: "u-012", entidadLabel: "Carlos Pinto",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "190.20.45.78",
  },
  {
    id: "al-021", timestamp: "2026-02-28T16:30:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Contrato", entidadId: "c-006", entidadLabel: "AMP-F2V9Q",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
  {
    id: "al-022", timestamp: "2026-02-27T11:15:00Z",
    usuarioId: "u-003", usuarioNombre: "Diego Muñoz",
    entidad: "Cliente", entidadId: "4", entidadLabel: "E-ShopChile",
    accion: "Editar", campo: "direccion", valorAnterior: "Cra. 7 #71-20, Bogotá", valorNuevo: "Cra. 7 #71-21, Bogotá",
    ip: "190.20.45.80",
  },
  {
    id: "al-023", timestamp: "2026-02-25T09:00:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Plan", entidadId: "plan-3", entidadLabel: "Enterprise",
    accion: "Editar", campo: "sucursalesMax", valorAnterior: "15", valorNuevo: "20",
    ip: "200.83.100.12",
  },
  {
    id: "al-024", timestamp: "2026-02-20T14:00:00Z",
    usuarioId: "u-004", usuarioNombre: "Laura Figueroa",
    entidad: "Tenant", entidadId: "0024", entidadLabel: "E-Shop Colombia",
    accion: "Editar", campo: "nombre", valorAnterior: "E-Shop CO", valorNuevo: "E-Shop Colombia",
    ip: "190.20.45.82",
  },
  {
    id: "al-025", timestamp: "2026-02-18T10:30:00Z",
    usuarioId: "u-001", usuarioNombre: "Fernando Roblero",
    entidad: "Trial Config", entidadId: "trial-2", entidadLabel: "Trial Enterprise 30d",
    accion: "Crear", campo: null, valorAnterior: null, valorNuevo: null,
    ip: "200.83.100.12",
  },
];
